### ISSUE TITLE
[Dossiers] Lien non-fonctionnel vers le nouveau dossier des dossiers multiples

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/Issues-Parlement#27]
Sur [ce dossier](http://www.assemblee-nationale.fr/15/dossiers/retablissement_confiance_action_publique.asp#confiance_action_publique), le lien vers le nouveau dossier législatif ne fonctionne pas:

![image](https://user-images.githubusercontent.com/1469823/40125071-45df1922-592a-11e8-9888-6f62277fbd41.png)

http://www.assemblee-nationale.fr/dyn/15/dossiers/retablissement_confiance_action_publique.asp

On dirait que le problème provient du "#" dans l'url qui est mangé à la place de ".asp", ex: www.assemblee-nationale.fr/14/dossiers/retablissement_confiance_action_publique.asp#test_oulala

**Comment by RouxRC** [comment]
Ça semble corrigé ?
Le lien vers [l'autre nouveau dossier](http://www.assemblee-nationale.fr/dyn/15/dossiers/confiance_action_publique) n'apparaît malheureusement pas par contre, il faudrait le récupérer via le dossier lié du premier dossier.

**Comment by mdamien** [comment]
Ils sont rapides !
