### ISSUE TITLE
[Dossiers] Étape superflue

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/Issues-Parlement#53]
*(je met directement le mail correspondant au problème)*

> 
> À: DIM <webmestre@assemblee-nationale.fr>
> Objet: Étape de seconde lecture superflue pour le PJL Justice
> Bonjour, 
> 
> Dans le dossier [Justice : loi de programmation 2018-2022 et de réforme](http://www.assemblee-nationale.fr/dyn/15/dossiers/reforme_justice_programmation_2018-2022?etape=15-SN2), il est indiqué une étape de seconde lecture au Sénat. Hors le texte n'as pas fait de seconde lecture au Sénat et est passé en CMP directement aprés la premiére lecture
> 
> Voici l'affichage erroné que l'on trouve donc sur le dossier de ce projet de loi:
> ![image](https://user-images.githubusercontent.com/1469823/52018879-30bbb300-24ec-11e9-88c1-e43fb715c195.png)
>
> Sur le [dossier du côté Sénat](http://www.senat.fr/dossier-legislatif/pjl17-463.html) on trouve le bon cheminement:
> ![image](https://user-images.githubusercontent.com/1469823/52019017-c1928e80-24ec-11e9-86cd-6ab63d3728f5.png)
>
> Est-il possible de corriger cet affichage incorrect ?
>
> En vous remerciant bien cordialement,

**Comment by boogheta** [comment]
@mdamien sorry je lagge complètement, tu as envoyé ce mail ou tu le mettais là pour qu'on le fasse ?
En tout cas le souci semble avoir été déjà corrigé à la source et le texte bien intégré jusqu'au texte disponible sur la fabrique https://www.lafabriquedelaloi.fr/articles.html?loi=pjl17-463
Du coup je ferme, mais n'hésite pas à rouvrir si besoin!
