### ISSUE TITLE
[Amendements] Mauvaise métadonnée auteur

### ISSUE THREAD

**Issue by David-Guillot** [regardscitoyens/Issues-Parlement#58]
Sur [cet amendement](http://www.assemblee-nationale.fr/dyn/15/amendements/1237/AN/2940) la métadonnée `AUTEUR_ID` vaut `757134`, ce qui ne correspond à aucun parlementaire dans la base de l'Assemblée ([son URL](http://www2.assemblee-nationale.fr/deputes/fiche/OMC_PA757134) retourne une 404). La valeur devrait être [719684](http://www2.assemblee-nationale.fr/deputes/fiche/OMC_PA719684).

**Comment by David-Guillot** [comment]
Rah, trouvé, c'est l'ID de la commission (tous les cas trouvés sont des amendements déposés par le rapporteur d'une commission) :man_facepalming:

**Comment by teymour** [comment]
L'API de NosDéputés.fr pourrait permettre de résoudre ce type d'incertitude concernant l'auteur.

Concernant cet exemple, cet amendement fait partie de la liasse mis à disposition concernant le texte numéo 1237 depuis l'url suivante : https://www.nosdeputes.fr/15/amendements/1237/json (dispo en xml et csv en changeant la dernière partie de l'url)

**Comment by RouxRC** [comment]
Je ferme cette issue qui n'en est du coup pas une, comme tu l'as compris, il s'agit des IDs des commissions que tu peux matcher dans l'opendata des "organes" de l'AN.
Il s'agit des cas pour lesquels une commission pour avis (pas saisie au fond donc) a adopté des amendements, qui sont donc ensuite repris par le rapporteur de cette commission en vue de les défendre en séance au nom de la commission. Le rapporteur n'en est donc pas vraiment l'auteur et c'est assez logique que ce soit la commission qui soit affectée. Du côté de ND comme le pointe @teymour nous ne rattachons pour ces cas là pas d'auteur.

**Comment by David-Guillot** [comment]
Yes merci à vous deux 👍
